name: "Blank issue"
description: Don't use this unless you are a Vike maintainer.
body:
  - type: markdown
    attributes:
      value: |
        # **Don't use this** unless you are a Vike maintainer. Create a new issue at [Vike's main repository `github.com/vikejs/vike`](https://github.com/vikejs/vike/issues/new/choose) instead.
  - type: textarea
    attributes:
      label: Description
