blank_issues_enabled: false
contact_links:
  - name: "💥 Bug"
    url: https://github.com/vikejs/vike/issues/new?template=bug.yml
    about: "Report a bug. (Redirects to Vike's main repository.)"
  - name: "🚀 Feature"
    url: https://github.com/vikejs/vike/issues/new?template=feature.yml
    about: "Suggest a new feature. (Redirects to Vike's main repository.)"
  - name: "✨ Polish"
    url: https://github.com/vikejs/vike/issues/new?template=polish.yaml
    about: "Unclear API or docs? Let us know — we'll polish Vike's DX. (Redirects to Vike's main repository.)"
  - name: "🙏 Help & Questions"
    url: https://github.com/vikejs/vike/discussions/new?category=help-questions
    about: "Get official help from Vike maintainers."
  - name: "🗨️ Other"
    url: https://github.com/vikejs/vike/discussions/new?category=other
    about: "Anything else: ideas, feedback, complaints, appreciation, ..."
  - name: "💬 Chit-chat"
    url: https://discord.com/invite/hfHhnJyVg8
    about: "Casual conversation with the community."
