name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install

      - name: Build vike-vue
        run: pnpm run build

      - name: Test building examples/basic
        run: pnpm run build
        working-directory: ./examples/basic
      - name: Test building examples/ssr-spa
        run: pnpm run build
        working-directory: ./examples/ssr-spa
      - name: Test building examples/with-vue-plugin
        run: pnpm run build
        working-directory: ./examples/with-vue-plugin

      - name: Test TypeScript examples/basic
        run: pnpm run test
        working-directory: ./examples/basic
      - name: Test TypeScript examples/ssr-spa
        run: pnpm run test
        working-directory: ./examples/ssr-spa
      - name: Test TypeScript examples/with-vue-plugin
        run: pnpm run test
        working-directory: ./examples/with-vue-plugin
